cargo-features = ["codegen-backend"]

[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
itertools = "0.13.0"
ratatui = "0.29.0"

[profile.dev]
codegen-backend = "cranelift"
